services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: desafio-bootcamp
    depends_on:
      db:
        condition: service_healthy
      localstack:
        condition: service_started
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      LOCALSTACK_ENDPOINT: http://localstack:4566
      APP_PUBLIC_URL: http://localhost:8080
      APP_STORAGE_LOCAL_DIR: /app/storage
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    ports:
      - "8080:8080"
    volumes:
      - ./.storage:/app/storage

  db:
    image: postgres:16-alpine
    container_name: postgres-bootcamp
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:4.0.0
    container_name: localstack-bootcamp
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - PERSISTENCE=1
    ports:
      - "4566:4566"
    volumes:
      - ./.localstack:/var/lib/localstack

volumes:
  postgres_data:
