spring:
  application:
    name: desafio-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/bootcamp_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml