spring:
  application:
    name: desafio-backend

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bootcamp_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
  config:
    import: optional:file:.env

app:
  public-url: ${APP_PUBLIC_URL:http://localhost:8080}

jwt:
  secret: ${JWT_SECRET:change-this-secret}
  expiration: ${JWT_EXPIRATION:86400000}

aws:
  region: ${AWS_REGION:sa-east-1}
  s3:
    bucket: ${AWS_S3_BUCKET:backend-challenge-images}
    endpoint: ${LOCALSTACK_ENDPOINT:http://localhost:4566}
    access-key: ${AWS_ACCESS_KEY_ID:test}
    secret-key: ${AWS_SECRET_ACCESS_KEY:test}

experience:
  level:
    base-xp-to-level-up: ${EXPERIENCE_LEVEL_BASE_XP:100}
    multiplier: ${EXPERIENCE_LEVEL_MULTIPLIER:1.08}
  check-in:
    participant-xp: ${EXPERIENCE_CHECK_IN_PARTICIPANT_XP:25}
    creator-xp: ${EXPERIENCE_CHECK_IN_CREATOR_XP:5}
